kind: Service
apiVersion: v1
metadata:
  name: passfail
  labels:
    app: passfail
    
spec:
  type: NodePort
  selector:
    app: passfail
  ports:
  - port: 8091
    name: http
    targetPort: 8091
  - port: 8090
    name: tracing
    targetPort: 8090
  - port: 8080
    name: jmx
    targetPort: 8080
 