apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: passfail
  name: passfail
  namespace: openshift-monitoring
spec:
  endpoints:
    - interval: 2m
      port: prom
      scrapeTimeout: 2m
    - interval1: 30s
      port: http1
  namespaceSelector:
    matchNames:
    - eonsmartcamera-dev-app
    - eonsmartcamera-devops-app
    
  selector:
    matchLabels:
      app: passfail